name: counter_app
description: Example app for reduced_solidart.
publish_to: 'none' 
version: 0.2.1+2

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 0.2.1
  reduced_solidart: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
